name: New Workflow

on:
  push:
    branches:
      - branch-1
  pull_request:
    branches:
      - branch-2
  workflow_dispatch:
    
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo -ne '3\r'
          sleep 1
          echo -ne '2\r'
          sleep 1
          echo -ne '1\r'
          sleep 1
          echo -ne 'Hello World\r'
          sleep 1
          echo -ne '\n'
  calculate-sum:
    runs-on: ubuntu-latest
    steps:
      - name: Add two numbers
        run: |
          echo -ne 'Connecting to satelite..\r'
          sleep 5
          echo -ne 'Performing quantum algorithms..\r
          sleep 5
          echo -ne "The sum of 5 and 10 is ${{ 5 + 10 }}"
          sleep 1
          echo -ne '\n'


